server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
        - id: email
          uri: lb://email
          predicates:
            - Path=/email/**
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/reg/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: prepaid
          uri: lb://prepaid
          predicates:
            - Path=/prepaid/**
        
   
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"         
            